import config from '../config'
const Images = {
    default_symbol:'https://drive.google.com/thumbnail?id=1RHt9vhUZdUlzEJwO6du8JJRwsfCXSr3I',
    ico_pathology:config.baseurl + "assets/images/icon/pathology.png",
    ico_pharmacy:"https://drive.google.com/thumbnail?id=1RHt9vhUZdUlzEJwO6du8JJRwsfCXSr3I",
    ico_doctor:config.baseurl + "assets/images/icon/doctor.png",
    ico_seva_kendra:config.baseurl + "assets/images/icon/pathology.png",
    ico_service:config.baseurl + "assets/images/icon/service.png",
    ico_app:config.baseurl + "assets/images/bluelogo_7.png",
    Board1:require('../assets/image/onboard_1.png'),
    Board2:require('../assets/image/onboard_2.png'),
    Board3:require('../assets/image/onboard_3.png'),
    otp1:require('../assets/image/otp1.png'),
    otp2:require('../assets/image/otp2.png'),
    check:require('../assets/image/check.png'),
    flag:require('../assets/image/flag.png'),
    blood:require('../assets/image/list-items/blood.png'),
    cancer:require('../assets/image/list-items/cancer.png'),
    child:require('../assets/image/list-items/child.png'),
    coronavirus:require('../assets/image/list-items/coronavirus.png'),
    doctor:require('../assets/image/list-items/doctor.png'),
    eye:require('../assets/image/list-items/eye.png'),
    health:require('../assets/image/list-items/health.png'),
    homeopathy:require('../assets/image/list-items/homeopathy.png'),
    kidney:require('../assets/image/list-items/kidney.png'),
    lungs:require('../assets/image/list-items/lungs.png'),
    mental:require('../assets/image/list-items/mental.png'),
    nose:require('../assets/image/list-items/nose.png'),
    pharmacy:require('../assets/image/list-items/pharmacy.png'),
    sex:require('../assets/image/list-items/sex.png'),
    spots:require('../assets/image/list-items/spots.png'),
    stomach:require('../assets/image/list-items/stomach.png'),
    teeth:require('../assets/image/list-items/teeth.png'),
    cat_pharmacy:require('../assets/image/cat_pharmacy.png'),
    cat_doctor:require('../assets/image/cat_doctor.png'),
    cat_lab:require('../assets/image/cat_lab.png'),
    key_bone:require('../assets/image/bone.png'),
    key_brain:require('../assets/image/brain.png'),
    key_ear:require('../assets/image/ear.png'),
    key_endocrine:require('../assets/image/endocrine.png'),
    key_female:require('../assets/image/female.png'),
    key_hair:require('../assets/image/hair.png'),
    key_hand:require('../assets/image/hand.png'),
    key_heart:require('../assets/image/heart.png'),
    key_kidney:require('../assets/image/kidney.png'),
    key_lungs:require('../assets/image/lungs.png'),
    key_male:require('../assets/image/male.png'),
    key_stome:require('../assets/image/stome.png'),
    key_tooth:require('../assets/image/tooth.png'),
    key_virus:require('../assets/image/virus.png'),
    key_vision:require('../assets/image/vision.png'),
    ico_prescription:require('../assets/image/prescription.png'),
    ico_camera:require('../assets/image/ico_camera.png'),
    ico_gallery:require('../assets/image/ico_gallery.png'),
}


export default Images